[build]
define_macros = []
extra_compile_args = []
include_dirs = []
libraries = []
library_dirs = []
undef_macros = []

[info]
github_username = "pymt-lab"
plugin_author = "csdms"
plugin_author_email = "csdms@colorado.edu"
plugin_license = "MIT"
summary = "PyMT plugin for CEM"

[library]
entry_point = ["Cem=bmi_cem:register_bmi_cem", "Waves=bmi_waves:register_bmi_waves"]
language = "c"

[plugin]
name = "cem"
requirements = ["cem"]

