build:
  define_macros: []
  extra_compile_args: []
  include_dirs: []
  libraries:
  - bmi_cem
  library_dirs: []
  undef_macros: []
info:
  github_username: mcflugen
  plugin_author: Eric Hutton
  plugin_license: MIT
  summary: PyMT plugin for CEM
library:
  entry_point: Cem=cem:Cem
  language: c
  register: register_bmi_cem
plugin:
  name: cem
  requirements:
  - cem
